version: '3.8'

services:
  accommodation-checker:
    volumes:
      - ./config.test.json:/app/config.json:ro
    environment:
      - CONFIG_PATH=/app/config.json
      - LOG_LEVEL=INFO
      - SINGLE_RUN=true
    restart: "no"  # Don't restart for test runs