services:
  # External mock notification service  
  mock-notification:
    build:
      context: ./docker
      dockerfile: Dockerfile.mock
    container_name: mock-notification-final
    ports:
      - "8082:3000"
    networks:
      - checker-network
    environment:
      - PORT=3000

networks:
  checker-network:
    driver: bridge