name: Check Gassho-zukuri Availability

on:
  schedule:
    # Run every 5 minutes
    - cron: '*/5 * * * *'
  workflow_dispatch: # Allow manual runs

jobs:
  check:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v3
    
    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v2
    
    - name: Build Docker image
      run: docker build -t gassho-tracker .
    
    - name: Run availability check
      env:
        MAILGUN_API_KEY: ${{ secrets.MAILGUN_API_KEY }}
        MAILGUN_DOMAIN: ${{ secrets.MAILGUN_DOMAIN }}
        NOTIFICATION_EMAIL: ${{ secrets.NOTIFICATION_EMAIL }}
      run: |
        docker run \
          -e MAILGUN_API_KEY="$MAILGUN_API_KEY" \
          -e MAILGUN_DOMAIN="$MAILGUN_DOMAIN" \
          -e NOTIFICATION_EMAIL="$NOTIFICATION_EMAIL" \
          -e SINGLE_RUN=true \
          gassho-tracker